### ISSUE TITLE
Does the docs need to be updated?

### ISSUE THREAD

**Issue by mvaneijgen** [vsupalov/docker-puppeteer-dev#2]
All I get with `make rebuild` is `make: *** No rule to make target `rebuild'.  Stop.` 

I have managed to get the docker image running with `docker-compose up` and everything seems to work, but it would be nice that the documentation is up to date. 

I also am trying to implement my own script, which proposes a challenge, I needed to update the packages, but each time it restored the default package.json with only `puppeteer` in it, what would be the best way to install my own dependancies?

Running on macOS 10.13.3

**Comment by vsupalov** [comment]
Thanks! You're right, the rebuild task was called restart. I fixed it, by renaming it to the "rebuild" which I pulled out of thin air when writing the docs it seems 😥 

Regarding your dependency issue, check out [this part](https://yarnpkg.com/lang/en/docs/cli/add/) of the yarn docs. Basically, you should install packages with `yarn add package_name`, and it will add those to your package.json and yarn.lock this way. Other methods don't persist in the files.

Hope that helps! Fixed it :)
